.NET Practical Assignment/Service-Booking-System-master/Service Booking System/Controllers/BookingController.cs
using OfficeOpenXml;
using OfficeOpenXml.Style;
using SBS.BAL.Interfaces;
using SBS.Model;
using Service_Booking_System.Utility;
using Service_Booking_System.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Service_Booking_System.Controllers
{
    public class BookingController : Controller
    {
        private IServiceManager _serviceManager;
    

        public BookingController(IServiceManager serviceManager)
        {
            
            _serviceManager = serviceManager;
           
        }
        
    // GET: Booking
    public ActionResult Index()
        {
            if(Session["user"]!=null && Session["role"].ToString() == "2")
            {
                var customer = (Customer)Session["user"];
                var bookingList = _serviceManager.GetBookingsByCustomerId(customer.Id);
                return View(bookingList);
            }
            if (Session["user"] != null && Session["role"].ToString() == "1")
            {
                
                var bookingList = _serviceManager.GetBookings();
                return View(bookingList);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult AddorEdit(int id=0)
        {
            if(Session["role"].ToString() == "1")
            {
                return RedirectToAction("Index", "Home");
            }
            if (Session["user"] != null )
            {
                var customer = (Customer)Session["user"];
                if (id==0)
                {
                    var services = _serviceManager.GetServices();
                    var vehicles = _serviceManager.GetVehiclesByOwnerId(customer.Id);
                    var bookingViewModel = new BookingViewModel
                    {
                        booking = new Booking() { BookingStart=DateTime.Now,BookingEnd=DateTime.Now},
                        services = services,
                        vehicles = vehicles
                    };

                    return View(bookingViewModel);
                }
                else
                {
                    var services = _serviceManager.GetServices();
                    var vehicles = _serviceManager.GetVehiclesByOwnerId(customer.Id);
                    var booking = _serviceManager.GetBooking(id);
                    var bookingViewModel = new BookingViewModel
                    {
                        booking = booking,
                        services = services,
                        vehicles = vehicles
                    };
                    return View(bookingViewModel);
                }
                
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AddorEdit(Booking booking)
        {
            if(ModelState.IsValid && Session["user"]!=null)
            {
                var customer = (Customer)Session["user"];
                booking.CustomerId = customer.Id;
                
                if(booking.Id != 0)
                {
                    booking.UpdatedBy = customer.Name;
                    booking.UpdatedOn = DateTime.Now;
                }
                else
                {
                    booking.CreatedBy = customer.Name;
                    booking.CreatedOn = DateTime.Now;
                    booking.UpdatedBy = customer.Name;
                    booking.UpdatedOn = DateTime.Now;
                }
               

                var vehicle = _serviceManager.GetVehicle(booking.VehicleId);
                var vehicleMake = vehicle.Make;
                var mechanic = _serviceManager.GetMechanicByMake(vehicleMake);
                if(mechanic != null)
                {
                    booking.MechanicId = mechanic.Id;
                }
                var result = _serviceManager.AddBooking(booking);
                TempData["SuccessMessage"] = "Booking added successfully";
                MyLogger.GetInstance().Info("Booking added successfully");
                return RedirectToAction("Index");
            }
            TempData["ErrorMessage"] = " Booking does not added";
            MyLogger.GetInstance().Info("Booking does not added");
            return RedirectToAction("Index", "Home");
        }

        public ActionResult DownloadExcel()
        {
            if (Session["user"] != null)
            {
                var customer = (Customer)Session["user"];
                var bookingList = _serviceManager.GetBookingsByCustomerId(customer.Id);
               
                ExcelPackage Ep = new ExcelPackage();
                ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
                Sheet.Cells["A1"].Value = "Id";
                Sheet.Cells["B1"].Value = "Service";
                Sheet.Cells["C1"].Value = "Mechanic";
                Sheet.Cells["D1"].Value = "Vehicle Number";
                Sheet.Cells["E1"].Value = "Booking Start Date";
                Sheet.Cells["F1"].Value = "Booking End Date";
                Sheet.Cells["G1"].Value = "Created By";
                Sheet.Cells["H1"].Value = "Created On";
                Sheet.Cells["I1"].Value = "Updated By";
                Sheet.Cells["J1"].Value = "Updated On";
                int row = 2;
                foreach (var item in bookingList)
                {
                    Sheet.Cells[string.Format("A{0}", row)].Value = item.Id;
                    var service = _serviceManager.GetService(item.ServiceId);
                    Sheet.Cells[string.Format("B{0}", row)].Value = service.Name;
                    var mechanic = _serviceManager.GetMechanic(item.MechanicId);
                    if(mechanic != null)
                    {
                        Sheet.Cells[string.Format("C{0}", row)].Value = mechanic.Name;
                    }
                    var vehicle = _serviceManager.GetVehicle(item.VehicleId);
                    Sheet.Cells[string.Format("D{0}", row)].Value = vehicle.LicensePlate;
                    Sheet.Cells[string.Format("E{0}", row)].Value = item.BookingStart;
                    Sheet.Cells[string.Format("F{0}", row)].Value = item.BookingEnd;
                    Sheet.Cells[string.Format("G{0}", row)].Value = item.CreatedBy;
                    Sheet.Cells[string.Format("H{0}", row)].Value = item.CreatedOn;
                    Sheet.Cells[string.Format("I{0}", row)].Value = item.UpdatedBy;
                    Sheet.Cells[string.Format("J{0}", row)].Value = item.UpdatedOn;
                    row++;
                }
                using (ExcelRange col = Sheet.Cells[2, 5, 2 + bookingList.Count, 5])
                {
                    col.Style.Numberformat.Format = "dd/MM/yyyy";
                    col.Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;
                }
                using (ExcelRange col = Sheet.Cells[2, 6, 2 + bookingList.Count, 6])
                {
                    col.Style.Numberformat.Format = "dd/MM/yyyy";
                    col.Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;
                }
                using (ExcelRange col = Sheet.Cells[2, 8, 2 + bookingList.Count, 8])
                {
                    col.Style.Numberformat.Format = "dd/MM/yyyy";
                    col.Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;
                }
                using (ExcelRange col = Sheet.Cells[2, 10, 2 + bookingList.Count, 10])
                {
                    col.Style.Numberformat.Format = "dd/MM/yyyy";
                    col.Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;
                }
                Sheet.Cells["A:AZ"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                Sheet.Cells["A:AZ"].AutoFitColumns();
                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader(
                    "content-disposition",
                    string.Format("attachment;  filename={0}", "Report.xlsx"));
                Response.BinaryWrite(Ep.GetAsByteArray());
                Response.End();

            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var result = _serviceManager.DeleteBooking(id);
            if (result != null)
            {
                TempData["SuccessMessage"] ="Booking deleted successfully";
                MyLogger.GetInstance().Info("Booking deleted successfully");
                return RedirectToAction("Index");
            }
            TempData["ErrorMessage"] = "Deletion is unsuccessfull";
            MyLogger.GetInstance().Info("Deletion is unsuccessfull");
            return RedirectToAction("Index");
        }
    }
}

.NET Practical Assignment/Service-Booking-System-master/Service Booking System/Controllers/DealerController.cs
using SBS.BAL.Interfaces;
using SBS.Model;
using Service_Booking_System.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Service_Booking_System.Controllers
{
    public class DealerController : Controller
    {

        private IServiceManager _serviceManager;

        public DealerController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }
        // GET: Dealer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddorEdit(int id = 0)
        {
            if (id == 0)
            {

                return View(new Dealer() { Id = 0 });
            }
            else
            {
                var user = _serviceManager.GetDealer(id);
                return View(user);
            }
        }

        [HttpPost]
        public ActionResult AddorEdit(Dealer dealer)
        {
            if (ModelState.IsValid)
            {
                dealer.RoleId = 1;
                var result = _serviceManager.AddDealer(dealer);
                TempData["SuccessMessage"] = result.Name + " registered successfully";
                MyLogger.GetInstance().Info(result.Name + " registered successfully");
                return RedirectToAction("Login", "Account");
            }
            TempData["ErrorMessage"] = "Dealer not registered";
            MyLogger.GetInstance().Info("Dealer not registered");
            return RedirectToAction("Login", "Account");
        }

        public ActionResult UserProfile(int id)
        {

            var dealer = _serviceManager.GetDealer(id);
            ViewBag.username = dealer.Name;
            if (dealer != null)
            {
                return View(dealer);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

.NET Practical Assignment/Service-Booking-System-master/Service Booking System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    ViewBag.Name = Session["name"];
    ViewBag.Id = Session["id"];
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/alertify.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-md bg-primary navbar-dark fixed-top shadow-sm main-nav">
        @Html.ActionLink("Service Booking", "Index", "Home", null, new { @class = "navbar-brand" })
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarCollapse">
            <div class="navbar-nav mr-auto">
                @if (Session["user"] != null && Session["role"].ToString() == "1")
                {
                    @Html.ActionLink("Customer", "Index", "Customer", null, new { @class = "nav-item nav-link active" })
                    @Html.ActionLink("Mechanic", "Index", "Mechanic", null, new { @class = "nav-item nav-link active" })
                    @Html.ActionLink("Service", "Index", "Service", null, new { @class = "nav-item nav-link active" })
                    @Html.ActionLink("Bookings", "Index", "Booking", null, new { @class = "nav-item nav-link active" })
                }


                @if (Session["user"] != null && Session["role"].ToString() == "2")
                {
                    @*@Html.ActionLink("Home", "Index", "Customer", null, new { @class = "nav-item nav-link active" })*@
                    @Html.ActionLink("Vehicle", "Index", "Vehicle", null, new { @class = "nav-item nav-link active" })
                    @Html.ActionLink("Bookings", "Index", "Booking", null, new { @class = "nav-item nav-link active" })

                }
            </div>
            <div class="navbar-nav">

                @if (Session["user"] != null && Session["role"].ToString() == "2")
                {
                    <a class="nav-link" href="@Url.Action("UserProfile", "Customer", new { id = ViewBag.Id })">Hello @ViewBag.Name </a>
                    @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "nav-item nav-link " })
                }
                else if (Session["user"] != null && Session["role"].ToString() == "1")
                {
                    <a class="nav-link" href="@Url.Action("UserProfile", "Dealer", new { id = ViewBag.Id })">Hello @ViewBag.Name </a>
                    @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "nav-item nav-link " })
                }
                else
                {
                    @Html.ActionLink("Register as Dealer", "AddorEdit", "Dealer", null, new { @class = "nav-item nav-link " })
                    @Html.ActionLink("Register as Customer", "AddorEdit", "Customer", null, new { @class = "nav-item nav-link " })
                    @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-item nav-link " })

                }



            </div>

        </div>
    </nav>
    <div class="container body-content" style="margin-top:90px">
        @RenderBody()


    </div>
    <footer>

        <div>&copy; @DateTime.Now.Year - My ASP.NET Application</div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>